version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

  worker:
    build: .
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    env_file:
      - ../.env
    depends_on:
      - redis

volumes:
  redis-data: 